services:
  core-api:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: local-ai-core-api
    ports:
      - "10010:10010"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
